// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://izqdlhimmjhbfayytegs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6cWRsaGltbWpoYmZheXl0ZWdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2ODA1NDMsImV4cCI6MjA2NzI1NjU0M30.3F__rvQJgQ_lIkSCpcmSLL7sR4KMU9YaDxhHisoq6zA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});